# Generated by Django 5.0.7 on 2024-12-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Token',
        ),
    ]
